### PR TITLE
Change height for PageContainer

### PR DESCRIPTION
**Pull request by emilyw26**
Changes the height for `PageContainer` to a larger value based on view height so that we can see all the content inside of the div

Before:
https://user-images.githubusercontent.com/16674015/235320246-15ef4fe0-4136-4dd0-a7f1-c07d067de01c.mov

After:
https://user-images.githubusercontent.com/16674015/235320182-b33af782-d818-4729-b795-334d7c20c15f.mov

### CODE REVIEW

**Comment by jacoblb64** [comment]
Seeing a weird discoloration on the tasks page that I'm not seeing on main, are you seeing this locally?
image

**Comment by emilyw26** [comment]
> Seeing a weird discoloration on the tasks page that I'm not seeing on main, are you seeing this locally? image

Yikes I wasn't seeing that before but after I pulled in the changes from main I'm seeing it. Looking into it now

**Comment by emilyw26** [comment]
@jacoblb64 fixed! I just sent the height to 95vh and that got rid of the issue

**Review by jacoblb64 — APPROVED** [review]
Weird, glad it was an easy fix!

**Pull request merged**
